version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mern-chat-app_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chatapp
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: 12345
    networks:
      - chat-app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern-chat-app_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:12345@mongo:27017/chatapp?authSource=admin
      - JWT_SECRET=piyush
    depends_on:
      - mongo
    networks:
      - chat-app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern-chat-app_frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - chat-app-network


volumes:
  mongo-data:

networks:
  chat-app-network:
    driver: bridge

